[pacman]
install = ['cava', 'btop', 'hyprland', 'nvim', 'wget', 'kitty', 'flatpak', 'rofi-wayland', 'sof-firmware', 'pipewire-pulse', 'unp']
[flatpak]
install = ['com.discordapp.Discord', 'org.vinegarhq.Sober', 'io.github.kukuruzka165.materialgram', 'com.ml4w.dotfilesinstaller', 'io.github.shiftey.Desktop']
