[pacman]
install = ['cava', 'btop', 'nvim', 'wget', 'zsh','kitty', 'flatpak', 'zoxide', 'sof-firmware', 'pipewire-pulse', 'unp', 'superfile', 'zen-browser-bin']
[flatpak]
install = ['com.discordapp.Discord', 'org.vinegarhq.Sober', 'io.github.kukuruzka165.materialgram', 'io.github.shiftey.Desktop']
[wget]
file = ['https://end-4.github.io/dots-hyprland-wiki/setup.sh']
location = ['~/']
[git] 
clone = ['https://github.com/WeirdTreeThing/chromebook-linux-audio.git']
location = ['~/git']
