[pacman]
install = ['cava', 'btop', 'github-desktop-bin', 'hyprland', 'hyprland', 'vim', 'wget', 'kitty', 'firefox', 'flatpak', 'rofi-wayland']
[flatpak]
install = ['app.zen_browser.zen', 'com.discordapp.Discord', 'org.vinegarhq.Sober','io.github.kukuruzka165.materialgram']
