
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[font]
size = 12.0
[env]
TERM = "xterm-256color"
[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
